{{- if (eq .Values.step "snapshot") -}}
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: {{ .Release.Name }}-{{ now | date "20060102" }}
spec:
  volumeSnapshotClassName: {{ .Values.install.volumesnapshotclass | quote }}
  source:
    persistentVolumeClaimName: {{ .Values.snapshot.name | quote }}
{{- end -}}